**Numpy -> Numerical Python**



In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
print(len(dir(np)))

532


**Built_in_functions in NumPy**

- `array `
- `arange `
- `linespace `
- `ndim `
- `shape `
- `size`
- `zeros `
- `ones`
- `full `
- `reshape `
- `reshape (-1,1)`
- `reshape(1,-1)`
- `eye `
- `ravel `
- `transpose `
- `concatinate `
- `random `
- `random -> randint `
- `random -> randn`
- `random -> rand`
- `random -> random `
- `repeat `
- `axis=1`
- `axis=0`
- `sum `
- `max`
- `min`
- `argmax `
- `argmin `
- `matmul `

In [ ]:
# What is Dimension
# what is Data in the Dimension

In [ ]:
# array built_in_function in numpy is used to create a data in the form
# of dimension

In [ ]:
# 1D

import numpy as np

a = np.array([10,20,30,50,90])

print(a)

print(a.ndim)

print(a.shape)

print(a.size)

[10 20 30 50 90]
1
(5,)
5


In [ ]:
a = np.array([10,20,30,50,90])

print(a)

print(a[2])

[10 20 30 50 90]
30


In [ ]:
a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(a)

print(a.ndim)

print(a.shape)

print(a.size)

[[10 90 60]
 [55 44 76]
 [ 3 17 14]]
2
(3, 3)
9


In [ ]:
a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(a)

print(a[1][2])

[[10 90 60]
 [55 44 76]
 [ 3 17 14]]
76


In [ ]:
# arange = is a built in function in numpy which is used to create data in
# 1D this function will take starting point and ending point - 1

a = np.arange(21,27)
print(a)

print(a.ndim)

[21 22 23 24 25 26]
1


In [ ]:
a = np.arange(55,66)
print(a)
print(a.ndim)

[55 56 57 58 59 60 61 62 63 64 65]
1


In [ ]:
a = np.arange(1,61)
print(a)
print(a.ndim)

b = a.reshape(10,6)
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
(10, 6)


In [ ]:
a = np.arange(1,61).reshape(10,6)
print(a)
print(a.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
(10, 6)


In [ ]:
print(a[4][3])

28


In [ ]:
# 1d to 3D

a = np.arange(1,61).reshape(5,2,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [ ]:
a[2][0][3]

np.int64(28)

In [ ]:
# 1d to 3D

a = np.arange(1,61).reshape(2,6,5)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [ ]:
a[0][3][3]

np.int64(19)

In [ ]:
a[1][1][2]

np.int64(39)

In [ ]:
# reshape(-1,1) and reshape(1,-1)

a = np.array([10,50,90,11,14])
print(a)
print(a.ndim)
print(a.shape)


b = a.reshape(-1,1)
print(b)
print(b.ndim)
print(b.shape)

[10 50 90 11 14]
1
(5,)
[[10]
 [50]
 [90]
 [11]
 [14]]
2
(5, 1)


In [ ]:
# reshape(-1,1) and reshape(1,-1)

a = np.array([10,50,90,11,14])
print(a)
print(a.ndim)
print(a.shape)


b = a.reshape(1,-1)
print(b)
print(b.ndim)
print(b.shape)

[10 50 90 11 14]
1
(5,)
[[10 50 90 11 14]]
2
(1, 5)


In [ ]:
# linespace

a = np.linspace(10,20,6)
print(a)

[10. 12. 14. 16. 18. 20.]


In [ ]:
# zeros

a = np.zeros((4,5))
print(a)

print(a.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [ ]:
# zeros

a = np.zeros((4,5) , dtype=np.float16)
print(a)

print(a.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float16


In [ ]:
# zeros

a = np.zeros((4,5) , dtype=np.int8)
print(a)

print(a.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int8


In [ ]:
# ones

a = np.ones((5,6) , dtype=np.int8)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [ ]:
# full

a = np.full((4,5) , 7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
# eye

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# ravel = any dim into 1D

a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(a)

b = a.ravel()
print(b)

[[10 90 60]
 [55 44 76]
 [ 3 17 14]]
[10 90 60 55 44 76  3 17 14]


In [ ]:
# concatinate

a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])
b = np.array([ [1,2,3] , [5,6,7] , [10,11,12] ])

print(a)
print(b)

c = np.concatenate((a,b))
print(c)

[[10 90 60]
 [55 44 76]
 [ 3 17 14]]
[[ 1  2  3]
 [ 5  6  7]
 [10 11 12]]
[[10 90 60]
 [55 44 76]
 [ 3 17 14]
 [ 1  2  3]
 [ 5  6  7]
 [10 11 12]]


In [2]:
import numpy as np

In [4]:
# Transpose = rows to columns and columns to rows

a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])
print(a)

print()


b = np.transpose(a) # a.T
print(b)

[[10 90 60]
 [55 44 76]
 [ 3 17 14]]

[[10 55  3]
 [90 44 17]
 [60 76 14]]


In [10]:
# random -> randint = between range randomly int values will be picked

a = np.random.randint(10,50,5)

print(a)

[13 25 25 16 23]


In [11]:
# random -> rand = based on rows and columns 0 to 1 random values will come

a = np.random.rand(5,6)
print(a)

[[0.46383463 0.75274972 0.56065663 0.57249617 0.29728026 0.21561327]
 [0.25354332 0.3497482  0.08410931 0.30055801 0.52778798 0.18124831]
 [0.64852711 0.96099649 0.12092388 0.2318123  0.55361538 0.2556543 ]
 [0.7921027  0.41013118 0.76555469 0.94620392 0.16947365 0.17617213]
 [0.96181566 0.57986925 0.88059933 0.11655673 0.3940072  0.73290386]]


In [13]:
# random -> randn = based on rows and columns -3 to 3 random values will come

a = np.random.randn(5,6)
print(a)

[[ 0.96632376 -0.26911287 -1.39213446 -0.50238922 -0.33086977 -0.53120894]
 [-1.24964377  1.2799891   1.42993621  0.91587966  0.18157573 -0.687156  ]
 [ 2.89449973 -0.79282201 -0.72684397  0.57541028 -0.69231487 -0.4396499 ]
 [ 0.40940818  1.40131171  0.55888678  0.58384352  0.68567474  1.02605057]
 [ 0.6445817  -2.17453779 -0.49702117  0.24526055 -0.50984052 -0.20110351]]


In [15]:
# random -> random = same like rand will give values between 0 to 1

a = np.random.random((5,6))
print(a)

[[0.50418638 0.26712629 0.09534407 0.12672869 0.97439434 0.72751698]
 [0.0731463  0.40008548 0.19254781 0.33427706 0.19656627 0.27814272]
 [0.67429505 0.49465801 0.89168872 0.54299106 0.03281598 0.6518715 ]
 [0.87672362 0.9458778  0.00244235 0.16086997 0.99715266 0.75156568]
 [0.03274045 0.3562645  0.12690111 0.73831641 0.32468989 0.10163164]]


In [16]:
# math operations in numpy

In [17]:
a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(np.max(a))

90


In [18]:
print(np.min(a))

3


In [19]:
print(np.sum(a))

369


In [20]:
# axis = 1 (row)
# axis = 0 (column)

In [21]:
a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(np.max(a))

90


In [26]:
print(np.sum(a , axis = 0))

[ 68 151 150]


In [23]:
print(np.max(a , axis = 0))

[55 90 76]


In [22]:
print(np.max(a , axis = 1))

[90 76 17]


In [28]:
a = np.array([  [10,90,60] , [55,44,76] , [3,17,14] ])

print(np.argmax(a))

1


In [30]:
print(np.argmin(a))

6


In [34]:
print(np.argmin(a))

6


In [35]:
print(np.argmax(a , axis = 1))

[1 2 1]


In [36]:
print(np.argmin(a , axis = 0))

[2 2 2]


In [37]:
a = np.array([ [10,1] , [3,9] ])
b = np.array([ [4,6] , [7,2] ])

print(np.add(a,b))

[[14  7]
 [10 11]]


In [39]:
a= np.array([ [1,4] , [3,2] ])
b = np.array([ [2,1,10] , [11,14,7] ])


print(a)
print()
print(b)

[[1 4]
 [3 2]]

[[ 2  1 10]
 [11 14  7]]


In [40]:
print(np.matmul(a,b))

[[46 57 38]
 [28 31 44]]


In [41]:
a= np.array([ [1,4] , [3,2] ])
b = np.array([ [2,1,10] , [11,14,7] , [10,20,1]])


print(a)
print()
print(b)

[[1 4]
 [3 2]]

[[ 2  1 10]
 [11 14  7]
 [10 20  1]]


In [42]:
print(np.matmul(a,b))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [46]:
# repeat

a = np.arange(50,61)
print(a)
print(a.shape)
print(a.ndim)


b = a.reshape(1,-1)
print(b)
print(b.shape)
print(b.ndim)

[50 51 52 53 54 55 56 57 58 59 60]
(11,)
1
[[50 51 52 53 54 55 56 57 58 59 60]]
(1, 11)
2


In [51]:
# repeat

a = np.arange(50,61)

b = a.reshape(1,-1) # 1d to 2d

c = np.repeat(b , 10 , axis = 0)
print(c)

[[50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]
 [50 51 52 53 54 55 56 57 58 59 60]]


In [55]:
# loop for numpy

f = np.array([ [2,1,10] , [11,14,7] , [10,20,1]])

p = []

for i in f:
  t = 0
  for j in i:
    t = t + j

  p.append(t)

print(p)

[np.int64(13), np.int64(32), np.int64(31)]
